version: '3'
services:
  nginx:
    image: harbor.chay-techs.com/reverseproxy/main_reverse_proxy-nginx:latest
    restart: always
    ports:
      - 80:8080
      - 443:443
    volumes:
      - ./nginx/log:/var/log/nginx